### PR TITLE
test pr

### PR DESCRIPTION
**Pull request by piotrnarajowski**

### CODE REVIEW

**Comment by piotrnarajowski** [comment]
#AutoPTS run zephyr MICP/CL/CGGIT/CHA/BV-01-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/piotrnarajowski/auto-pts/pull/2#issuecomment-2049648881 after 15:05:08.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/piotrnarajowski/auto-pts/pull/2#issuecomment-2049648881 after 15:07:48.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/piotrnarajowski/auto-pts/pull/2#issuecomment-2049640216 after 15:12:07.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/piotrnarajowski/auto-pts/pull/2#issuecomment-2049858561 after 16:46:54.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>MICS    MICS/SR/SGGIT/SER/BV-01-C       PASS</details>

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/piotrnarajowski/auto-pts/pull/2#issuecomment-2069112140 after 13:08:13.

**Pull request merged**
